### ISSUE TITLE
Binary dependencies

### ISSUE THREAD

**Issue by est31** [wistein/TourCount#1]
For packaging inside f-droid, it would be needed to have no binary dependencies. Is it possible to not include the commons-lang.jar file but instead getting it from maven central, or from jitpack (https://jitpack.io)?

**Comment by wistein** [comment]
Yes, is possible. 
I put the commons-lang3-3.1.jar file into the GIT repository as I thought it could be of interest.
It is just the default library from maven used by Android Studio.

Remark: 
Today I fixed a bug regarding LocationService in the module CountingActivity.java and provided also the new tourcount-release.apk.

Best regards
Wilhelm Stein

-----Ursprüngliche Nachricht-----
Von: est31 [mailto:notifications@github.com] 
Gesendet: Mittwoch, 3. August 2016 20:07
An: wistein/TourCount
Betreff: [wistein/TourCount] Binary dependencies (#1)

For packaging inside f-droid, it would be needed to have no binary dependencies. Is it possible to not include the commons-lang.jar file but instead getting it from maven central, or from jitpack (https://jitpack.io)?

**Comment by est31** [comment]
Can you also do it inside the repo? Its much easier for f-droid then.

**Comment by wistein** [comment]
I removed it from the repo.

**Comment by est31** [comment]
Many thanks!

Little question: can you try to give your commit commit titles, so that everyone knows what you are doing in your commits? That would be great, but its no requirement for f-droid. I'll package 2.0.6 soon.

**Comment by wistein** [comment]
Thank you for your support.

-----Ursprüngliche Nachricht-----
Von: est31 [mailto:notifications@github.com] 
Gesendet: Donnerstag, 4. August 2016 00:06
An: wistein/TourCount
Cc: Wilhelm Stein; Comment
Betreff: Re: [wistein/TourCount] Binary dependencies (#1)

Many thanks!

Little question: can you try to give your commit commit titles, so that everyone knows what you are doing in your commits? That would be great, but its no requirement for f-droid. I'll package 2.0.6 soon.

**Comment by est31** [comment]
Hrmm.... Now the problem is that the build fails. Maybe forgot to specify the maven dependency?

**Comment by wistein** [comment]
I have only a rough knowledge about the internal mechanisms of Android Studio and thought the library dependencies would be  included automatically.

Can you give me a hint how to fix that?

Thanks, and please excuse 

Von: est31 [mailto:notifications@github.com] 
Gesendet: Donnerstag, 4. August 2016 00:36
An: wistein/TourCount
Cc: Wilhelm Stein; Comment
Betreff: Re: [wistein/TourCount] Binary dependencies (#1)

Hrmm.... Now the problem is that the build fails. Maybe forgot to specify the maven dependency?

**Comment by wistein** [comment]
Add-on:
I'm solving this problem by substituting all the StringUtils library-related calls in the java modules with corresponding source functions.
Then there is no need for this library anymore.
Next commit will have this fixed.

-----Ursprüngliche Nachricht-----
Von: est31 [mailto:notifications@github.com] 
Gesendet: Donnerstag, 4. August 2016 00:36
An: wistein/TourCount
Cc: Wilhelm Stein; Comment
Betreff: Re: [wistein/TourCount] Binary dependencies (#1)

Hrmm.... Now the problem is that the build fails. Maybe forgot to specify the maven dependency?

**Comment by wistein** [comment]
1. add-on:
   Commit with fixes is done.

-----Ursprüngliche Nachricht-----
Von: stein.wm [mailto:stein.wm@web.de] 
Gesendet: Donnerstag, 4. August 2016 16:53
An: 'wistein/TourCount'
Betreff: AW: [wistein/TourCount] Binary dependencies (#1)

Add-on:
I'm solving this problem by substituting all the StringUtils library-related calls in the java modules with corresponding source functions.
Then there is no need for this library anymore.
Next commit will have this fixed.

-----Ursprüngliche Nachricht-----
Von: est31 [mailto:notifications@github.com] 
Gesendet: Donnerstag, 4. August 2016 00:36
An: wistein/TourCount
Cc: Wilhelm Stein; Comment
Betreff: Re: [wistein/TourCount] Binary dependencies (#1)

Hrmm.... Now the problem is that the build fails. Maybe forgot to specify the maven dependency?

**Comment by est31** [comment]
Okay, now it looks much better, thank you!

Last question, to make it easier for f-droid packaging: always create a git tag tag with the commit that you want to have the given version. So if you want commit 0c3d71e8e492d02acdee775a7a5f3bb71e543b3a to have version 2.0.7, then tag that one with the tag 2.0.7.

Because right now its not clear whether 0c3d71e8e492d02acdee775a7a5f3bb71e543b3a or 21261844fb9ec2d45a620ccdb67ac31bf6a3cbe5 should be the 2.0.7 version, and even if you tell me now, its not clear for the future. Therefore, best tag your releases.

I'll include commit 
0c3d71e8e492d02acdee775a7a5f3bb71e543b3a as 2.0.7 into f-droid now.

**Comment by wistein** [comment]
Thank you very much for your help and patience.

Well, commit 0c3d71e is ok, as I only reformatted the code and changed some comments in the 2 following commits.

I will tag an important commit in the future like you proposed.

E.g.: Bug fix, new function x, V. 2.0.8

Von: est31 [mailto:notifications@github.com] 
Gesendet: Freitag, 5. August 2016 08:53
An: wistein/TourCount
Cc: Wilhelm Stein; Comment
Betreff: Re: [wistein/TourCount] Binary dependencies (#1)

Okay, now it looks much better, thank you!

Last question, to make it easier for f-droid packaging: always create a git tag tag with the commit that you want to have the given version. So if you want commit  https://github.com/wistein/TourCount/commit/0c3d71e8e492d02acdee775a7a5f3bb71e543b3a 0c3d71e to have version 2.0.7, then tag that one with the tag 2.0.7.

Because right now its not clear whether  https://github.com/wistein/TourCount/commit/0c3d71e8e492d02acdee775a7a5f3bb71e543b3a 0c3d71e or  https://github.com/wistein/TourCount/commit/21261844fb9ec2d45a620ccdb67ac31bf6a3cbe5 2126184 should be the 2.0.7 version, and even if you tell me now, its not clear for the future. Therefore, best tag your releases.

I'll include commit 
 https://github.com/wistein/TourCount/commit/0c3d71e8e492d02acdee775a7a5f3bb71e543b3a 0c3d71e as 2.0.7 into f-droid now.
