### ISSUE TITLE
The app crashes while clicking on EXPORT DATA to CSV file. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [wistein/TourCount#16]
#### Expected behavior
While clicking on EXPORT to CSV file, it must be exported. 

#### Actual behavior
It crashes while clicking on Export to CSV file. 

#### How to reproduce
Install app from F droid. 

Press on 3 dots placed on the top right corner. 

It shows some options. 

Press on EXPORT DATA->CSv file. 

It crashes while clicking on it. 

* Browser: Tour Count
* Version:2.4.5
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/KjwhEDTy4zc
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/the-app-crashes-while-clicking-on-export-data-to-csv-file">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wistein** [comment]
I hope to have it fixed in version 3.0.0 which is coming soon.

In the meantime please, try the following:
- Upgrade to version 2.4.6.
- Download the example basic DB-file from https://github.com/wistein/TourCount/tree/master/docs/tourcount0.db.
- Put it in your user basic directory (/storage/emulated/0).
- Start TourCount and import this as Basic DB.
- You may edit it to your liking.

After that it should work as expected.

Please read and follow the documentation before using the app, then this crash would not occur.
Once the database is loaded correctly, there should be no crash anymore.
